### ISSUE TITLE
Option to set tagdir

### ISSUE THREAD

**Issue by joereynolds** [jsfaint/gen_tags.vim#11]
Currently (like you said in #9), the file for `tags` generated by `ctags` resides in `$HOME/.cache/tags_dir`.
I think most people (me included) would prefer this to be in the top level of the project directory so that Vim automatically picks it up.

**Comment by jsfaint** [comment]
`gen_tags.vim` will call `set tags` for you after ctags generated.
![image](https://user-images.githubusercontent.com/571829/27629066-a964b5f6-5c23-11e7-87de-5bed8ded478d.png)

**Comment by joereynolds** [comment]
Oh, thanks!
Does tags need to already be defined in my init.vim?
I don't have any `tags=` assignments at the moment

**Comment by jsfaint** [comment]
No need to set in init.vim, `gen_tags.vim` will do everything for you 😄 
You can check it with `:set tags`
