### ISSUE TITLE
Idea: set tags to .git/tags_dir instead of ~/.cache/tags_dir?

### ISSUE THREAD

**Issue by ahmedelgabri** [jsfaint/gen_tags.vim#14]
I like how simple this plugin is & how good it works. But one thing I think it can be better is where it stores the tags files. Right now it stores them in `~/.cache/tags_dir` which is ok, but I think it might be better to store them in `.git/tags_dir`.

This will make cleaning up tags files easier, because if you delete a project folder then you clear the tags files too + since the plugin already knows where is the `.git` folder this shouldn't be a big deal.

What do you think?

**Comment by jsfaint** [comment]
Good idea, thanks for advice.
But a little problem here is how shall we handle non-git source code?
Maybe just leave them in ~/.cache/tag_dir?

**Comment by jsfaint** [comment]
Maybe I can add an option for it.
If the option is set, generate tags in project folder, otherwise generate tags in cache folder

**Comment by jsfaint** [comment]
@ahmedelgabri I do some experiment on `ctags` branch, please take some time and have a look.
Wait for your advices 😄 Thanks

I add an option `g:gen_tags#ctags_use_cache_dir`, this variable is set to `1` by default. (To keep the old habit)
It will use `$HOME/.cache/tag_dir` as the base directory.

If you set this variable to 0 in your vimrc, it has two different behaviors:

* git repo

  It will use `<project folder>/.git/tag_dir` as tags dir

* non-git repo

  It will use `<project folder>/.tag_dir` as tags dir

**Comment by ahmedelgabri** [comment]
Wow that was fast! 😄 

One thing though, I think the plugin should always fallback to `~/.cache/tag_dir` 

Will try the branch & let you know, thanks!

**Comment by ahmedelgabri** [comment]
You are missing an `endif` [here](https://github.com/jsfaint/gen_tags.vim/commit/b1341c581f9c726ddd0a45f3af1f2d93d486dc95#commitcomment-23387227)

Also, I get these errors 
<img width="637" alt="screen shot 2017-07-31 at 10 09 13" src="https://user-images.githubusercontent.com/63876/28768571-752f2cc0-75d8-11e7-8b37-0ad1873ec89c.png">

These are my settings

```vim
Plug 'jsfaint/gen_tags.vim', { 'branch': 'ctags' }
let g:loaded_gentags#gtags = 1
let g:gen_tags#ctags_auto_gen = 1
let g:gen_tags#ctags_use_cache_dir = 0
let g:gen_tags#verbose = 1
```

and I'm using `neovim` `HEAD`

**Comment by jsfaint** [comment]
Sorry for the typo, should be works now.

But I can't reproduce "E730: using List as a string" issue, I used `neovim 0.2.0` both on windows and linux.
For my guess, maybe the parameter  format of job is changed in `neovim HEAD` version?
![image](https://user-images.githubusercontent.com/571829/28770249-0db3a34e-7611-11e7-9c9e-9cac32e9301b.png)

**Comment by ahmedelgabri** [comment]
I dunno if that changed in `HEAD` but that's very minor for now it affects `let g:gen_tags#verbose = 1` so I'll disable this for now anyway. Thanks for the fix!

**Comment by jsfaint** [comment]
OK, Thanks for clarify.

I found a neovim issue comment here.
https://github.com/neovim/neovim/issues/4266#issuecomment-189366997

It looks I need to modify the `s:job_stdout()` function.

Thanks again, I will merge `ctags` branch to `master` branch later.

**Comment by ahmedelgabri** [comment]
I think for non-git repos the plugin should fallback to `$HOME/.cache/tags_dir` instead of `<project folder>/.tags_dir` what do you think?

**Comment by ahmedelgabri** [comment]
Oops too late? 😄

**Comment by jsfaint** [comment]
😄 It's never too late to get a good suggestion.
I believe it's an option too.

**Comment by ahmedelgabri** [comment]
Haha. So the main idea is that if you have a git repo & you want store the tags files inside of `.git` then you can do it, otherwise everything works as before.

**Comment by jsfaint** [comment]
OK~ I rewrite this part which cost less code 😃

**Comment by jsfaint** [comment]
@ahmedelgabri Please check `ctags` branch, did it work as your expect now?
Thanks 😄

**Comment by ahmedelgabri** [comment]
It works 👌🏼 thanks a lot @jsfaint!

**Comment by jsfaint** [comment]
I rollback master branch to previous commit, sorry for the inconvenient

**Comment by ahmedelgabri** [comment]
No worries, thanks!
