### ISSUE TITLE
Request: Blacklist Directories for Scanning

### ISSUE THREAD

**Issue by jalcine** [jsfaint/gen_tags.vim#19]
Thanks for making this project! I have a suggestion that I'd like to propose before making a PR.

I typically run Neovim from my home directory. I then open tabs to present a separate 'project' in Vim. I notice, however, that ctags gets triggered _immediately_ from start, which makes it run against my home directory. All 200,000 files begin getting tagged which eventually freezes up my computer. My proposal is to have a blacklist of exact matches of directories that should _not_ trigger a scan by gen_tags.vim.

**Comment by jsfaint** [comment]
Good idea!
If you have any implement already, please create a PR for it. 😄 
I need to find some spare time to do it this job later.

Thanks~

**Comment by jalcine** [comment]
Tight. I can definitely begin working on that.

**Comment by jsfaint** [comment]
Hi @jalcine I have a solution here, please check if it meet your request 😄 
Thanks

e.g.:

```viml
let g:gen_tags#blacklist = ['$HOME']
```

**Comment by jsfaint** [comment]
Hi @jalcine do you have any update?

**Comment by jalcine** [comment]
Slightly. So I noticed that my issue was with how this plugin determines that it was in a Git directory. I have a `.git` directory in my `$HOME`; which triggers a whole transversal of that directory for ctags. That's the actual problem I'm having.

I'll send PRs to resolve both.

**Comment by jalcine** [comment]
Hmm. Nope, that wasn't it. I'll still do this check tho.

**Comment by jsfaint** [comment]
Hi @jalcine Have you check the blacklist branch in my repo?
I just rebase it into single commit.

**Comment by jsfaint** [comment]
@jalcine 
> Hmm. Nope, that wasn't it. I'll still do this check tho.

It was caused by a mistake in commit fc88257ac5640c0c9edc5f065fbff81b8ef08c65, which is path convert issue. I already fixed it in commit a0a785eb677d51c38459e96798592694fb38fe8e

**Comment by jsfaint** [comment]
Fixed in #23
I tested on windows, linux and macOS, all work well
Thanks again @jalcine

**Comment by jalcine** [comment]
Ah solid. Thanks for that catch.
