### ISSUE TITLE
Add option to config ctags opts

### ISSUE THREAD

**Issue by elecalion** [jsfaint/gen_tags.vim#2]
Could you add a option like
g: ctags_opts = "--c++-kinds=+p --fields=+iaS --extra=+q"
to config ctags opts.

**Comment by jsfaint** [comment]
😄 Did you try gtags before? It's a better choice for C/C++ development.
I haven't use ctags for a long time in C/C++ after I met gtags

Or maybe some other plugins you used need the ctags tags file?

**Comment by elecalion** [comment]
I am using gtags, it's great. But C omni completion needs ctags tags. Those opts are just for completion.
Clang is another good choice for completion, while it makes lots of background process. C omni completion is thinner and simpler than Clang.

**Comment by jsfaint** [comment]
Added 😆 
BTW: I currently use [vim-clang](https://github.com/justmao945/vim-clang) for C/C++ completion.

**Comment by elecalion** [comment]
Thanks. Good job. ( ´∀`)

**Comment by jsfaint** [comment]
Hi @elecalion I add a prefix to the options, so you need to change your setting from `g:ctags_opts` to `g:gen_tags#ctags_opts`.
Sorry for the inconvience 😢

**Comment by elecalion** [comment]
Got it, thanks!
Actually, I have add a prefix in my own folk, but your way seems better.
