### ISSUE TITLE
the plugin is creating `.git/` folders 

### ISSUE THREAD

**Issue by ahmedelgabri** [jsfaint/gen_tags.vim#24]
This is my settings, but right now when I open a file in a directory that's not a git repo or subfolder of a git repo. It creates `.git/` folder to store the tags inside.

```vim
let g:loaded_gentags#gtags = 1
let g:gen_tags#ctags_auto_gen = 1
let g:gen_tags#ctags_use_cache_dir = 0
```

What I expect is the following since I have `let g:gen_tags#ctags_use_cache_dir = 0`
- When in a git repo (even in a subdirectory) the plugin should manage to find the root `.git/` folder & store the tags inside of it, if it failed then it should use the cache directory. 
- If I'm not inside a git repo, then it should store the tags files in the cache directory.

It was working like this before but maybe a recent change changed the behavior somehow.

**Comment by jsfaint** [comment]
Sorry for the inconvenience.
I think it's a mistake when I refactor git detection in this commit 7d69eda7fa4d1e0c8b4d3a6a8b63de8af14a7ee3
But I on vacation of national day and I don't have computer right now.
I'll fix it ASAP when I get home.

Sorry again :sob:

**Comment by ahmedelgabri** [comment]
No worries, enjoy your holiday 😊

**Comment by jsfaint** [comment]
@ahmedelgabri For now, can you do me a favor please?
What's the output of following command.

```
:echo gen_tags#get_scm_type()
:echo gen_tags#find_scm_root()
:echo gen_tags#find_project_root()
:echo g:gen_tags#ctags_use_cache_dir
```

Thank you~

**Comment by ahmedelgabri** [comment]
@jsfaint 

inside an empty buffer at `$HOME`

```vim
:echo gen_tags#get_scm_type() " output: nothing
:echo gen_tags#find_scm_root() " output: nothing
:echo gen_tags#find_project_root() " output: /Users/ahmed ($HOME)
:echo g:gen_tags#ctags_use_cache_dir " output: 0
```

inside an empty buffer in a git repo

```vim
:echo gen_tags#get_scm_type() " output: .git
:echo gen_tags#find_scm_root() " output: nothing
:echo gen_tags#find_project_root() " output: path to git repo root (/Users/ahmed/path/to/repo)
:echo g:gen_tags#ctags_use_cache_dir " output: 0
```

---
Then to reproduce the issue:

- `[n]vim foo.js` 
- type `function foo () {}`
- `:wq`
- `ls -al` (you will find a `.git` folder now)

inside `foo.js` in a git repo subdirectory or `$HOME` 

```vim
:echo gen_tags#get_scm_type() " output: .git
:echo gen_tags#find_scm_root() " output: nothing
:echo gen_tags#find_project_root() " output: path to subdirectory (/Users/ahmed/path/to/repo/subdirectory)
:echo g:gen_tags#ctags_use_cache_dir " output: 0
```

**Comment by jsfaint** [comment]
Thanks for the details!
It' clear now, a bug in `gen_tags#find_scm_root`

**Comment by jsfaint** [comment]
@ahmedelgabri Sorry for the long wait, I'm home now, but unfortunately I can't reproduce this issue.
Maybe there are some difference between our vimrc?

**Comment by jsfaint** [comment]
I also tried the dotfile from your github, can't reproduce it either
I can't see the this behavior
> ls -al (you will find a .git folder now)

There must be something wrong with my action step.

your dotfile is awesome by the way :+1:

**Comment by jsfaint** [comment]
Sorry for the long wait. I'm home now
I reproduced this issue with your dotfile, still tracking it.

BTW: your dotfile looks awesome :+1:

**Comment by jsfaint** [comment]
That's weird, I only reproduced this issue three times.
I can't find the correct step..

**Comment by jsfaint** [comment]
@ahmedelgabri I found some weird behavior with your dotfile. Maybe you can give me some advice here

# Experiment as below:
I write a simple vimscript to call some functions

echo.vim
```viml
echo 'scm_type: ' . gen_tags#get_scm_type()
echo 'scm_root: ' . gen_tags#find_scm_root()
echo 'project_root: ' . gen_tags#find_project_root()
echo 'ctags_auto_gen: ' . g:gen_tags#ctags_auto_gen
echo 'ctags_use_cache_dir: ' . g:gen_tags#ctags_use_cache_dir
```
## Experiment 1

In the home, run `vim` to open a empty buffer, then `:source echo.vim`

my config
![image](https://user-images.githubusercontent.com/571829/31285512-1aa53424-aa81-11e7-8acb-f9ac5b4dc2d2.png)

your config
![image](https://user-images.githubusercontent.com/571829/31285820-00dbaa5e-aa82-11e7-8b9e-df89afe704f4.png)

The behavior is same.

## Experiment 2

In a git repo, run `vim` to open a empty buffer, then `:source echo.vim`

my config
![image](https://user-images.githubusercontent.com/571829/31285894-2b5ca210-aa82-11e7-9250-04fe9e3f4dd1.png)

your config
![image](https://user-images.githubusercontent.com/571829/31285903-2f55eff2-aa82-11e7-86ef-e80a1634e369.png)

**￼`gen_tags#find_scm_root()` return '' with your config..**

## Expriment 3

Create `foo.js` in a empty folder, then `:source echo.vim`

my config
![image](https://user-images.githubusercontent.com/571829/31285972-5e8233c6-aa82-11e7-805d-5413b22650a4.png)

your config
![image](https://user-images.githubusercontent.com/571829/31286044-96dc36ae-aa82-11e7-895f-7baa64a296a6.png)

Behavior is same, but **there was no `.git` folder created**.

## Experiment 4

Open `plugin.vim` in a git repo, then `:source echo.vim`

my config
![image](https://user-images.githubusercontent.com/571829/31286155-e259ac88-aa82-11e7-981a-03c9c485e032.png)

your config
![image](https://user-images.githubusercontent.com/571829/31286162-e6c175f8-aa82-11e7-8020-085c94c64f21.png)

The result is same with experiment 2

**Comment by ahmedelgabri** [comment]
That's weird indeed & I don't have any idea why my config is doing this 🤔 Will try to look into this. BTW, I mainly use `nvim` but the behavior looks the same so this doesn't matter. 

> BTW: your dotfile looks awesome 👍

Thanks! if you have any ideas how to improve it more, feel free 😄

**Comment by jsfaint** [comment]
`gen_tags#find_scm_root()` return '' is caused by this setting in `plugin/settings.vim`

```viml
set wildignore+=*.o,*.out,*.obj,.git,*.rbc,*.rbo,*.class,.svn,*.gem,*.pyc
```

it ignores `.git` in vim, I guess

**Comment by ahmedelgabri** [comment]
`:h wildignore`

> 	A list of file patterns.  A file that matches with one of these
>	patterns is ignored when expanding |wildcards|, completing file or
>	directory names, and influences the result of |expand()|, |glob()| and
>	|globpath()| unless a flag is passed to disable this.

`:h expand()`

> When {expr} does not start with '%', '#' or '<', it is
> expanded like a file name is expanded on the command line.
> 'suffixes' and 'wildignore' are used, unless the optional
> {nosuf} argument is given and it is TRUE.


So maybe you will need to pass the `{nosuf}` flag _I assume you depend on one of `expand()`, `glob()` or `globpath()` or is it a bad idea? Because I think having `.git` in `wildignore` is very common in general & shouldn't affect the plugin too

**Comment by jsfaint** [comment]
@ahmedelgabri Thanks for the explanation, after add `{nosuf}` for `expand()` it works now.
![image](https://user-images.githubusercontent.com/571829/31291173-c58971c6-aa94-11e7-848e-1b50c79aa412.png)

Can you check if this issue is fixed? Thanks

**Comment by ahmedelgabri** [comment]
Tested & seems to be working fine now 👍 Thanks!

**Comment by jsfaint** [comment]
It's 2:00 am, I need to go sleep now.
Thanks for your great support.

**Comment by ahmedelgabri** [comment]
I got the error again, but this time the replication is a bit odd might be a combination of https://github.com/mhinz/vim-startify & your plugin somehow.

1. go to a git repo & open any file (just to add it to the list of MRU files in Startify)
2. go to `$HOME` & open vim
3. type `0` to open the file from Startify screen
4. close vim
5. open vim again (you should get the error)

**Comment by jsfaint** [comment]
@ahmedelgabri I reproduced this issue with startify.

```viml
scm_type: .git
scm_root: /Users/jiasui/repos/vimcfg
project_root: /Users/jiasui/repos/
ctags_auto_gen: 1
ctags_use_cache_dir: 0
```

That's because this code snippet

```vim
function! gen_tags#find_project_root() abort
  if exists('s:project_root')
    return s:project_root
  endif

 ...
endfunction
```

`s:project_root` was cached for some reason:
1. In the original code, `gen_tags.vim` use `system()` to find git repo root
It's boring in windows because the console windows
2. For non-git project, if you change the cwd will cause the project root change

But vim-startify will change the cwd which cause `gen_tags.vim` got different scm root and project root.
I'll try to fix this issue later, please wait..

**Comment by jsfaint** [comment]
You can also reproduce this issue by `:e` into a git repo folder

**Comment by ahmedelgabri** [comment]
Looks like it's fixed now, thanks again for your help & quick fixes :)

**Comment by jsfaint** [comment]
You're welcome, thanks for the report!

BTW I'm refactoring gtags support, add `use_cache_dir` for gtags, too
I need to change `g:gen_tags#ctags_use_cache_dir` to `g:gen_tags#use_cache_dir`
which will impact the existence setting, sorry for the inconvenience. 😢

**Comment by ahmedelgabri** [comment]
No worries & thanks for the heads up 👍
