### ISSUE TITLE
!global command doesn't work after update.

### ISSUE THREAD

**Issue by coil398** [jsfaint/gen_tags.vim#26]
After recent update, !global command doesn't work in vim.
Error: global command failed. command line: global --result=ctags-mod -qf 'hoge.py', or any other commands of global in vim.
When I disable gen_tags.vim, it works fine.

**Comment by jsfaint** [comment]
It works fine for me, maybe some setting is different?
![image](https://user-images.githubusercontent.com/571829/31604626-7f082efe-b296-11e7-9dcf-3a690435412c.png)
![image](https://user-images.githubusercontent.com/571829/31604686-a7135f2c-b296-11e7-97b2-ae402ac4a009.png)

**Comment by coil398** [comment]
Thx for the quick response.

I did some experiments.

sorry, I misunderstood.
I finally know the !global command gets tags from GTAGS, GPATH and GRTAGS from ~/.cache/tags_dir/{sth} directory, not the same directory of the files, and need to make the tags files in it by executing :GenGTAGS.

It works OK on macOS, however in case which on debian 9, just the homeparallels(because I use debian9 on Parallels on macOS, home folder is /home/parallels/) folder and tags files in it are made in ~/.cache/tags_dir by executing :GenTAGS.
And the !global command shows an error, global: 'sth' is not a source file.

**Comment by jsfaint** [comment]
Sorry for the inconvenience, I changed the behavior in recently commit.
The db dir is set via `g:gen_tags#use_cache_dir` now.
The variable is 1 by default, and the db dir is `$HOME/.cache/tags_dir`.
If this variable is set to 0 and if the project is a git/svn/hg repo, the db dir will be `<repo>/.git/tags_dir/`

Sorry, I don't have parallel environment to test this issue. 
Can you please check the version of global that you used on debian 9.
I just found http://mirrors.ustc.edu.cn/debian/pool/main/g/global/ this in debian mirror.
It looks debian still provide the old version of global.

Does your system have multiple global installed?
Thanks

**Comment by coil398** [comment]
All right, I got it from README.md.
I understood how cache works.OK.

Now, I checked the version of global and gtags on debian9.
global was v6.5.7, and gtags was v6.5.6, but on mac they both were v6.5.7.
So, I built the newer one, then I tried making tags.
Apparently, creating tags files is ok, I guess the difference between macOS and debian9(probably other linux os)is the name of the folder in tags_dir.

I started a new environment on ubuntu16, then installed necessary libs, made a small file with python and made tags files.
The name of tags files in tags_dir was the same as the ones on debian9, however it worked.
And next I tried it on debian,so it worked fine for some reason.
The difference between debian and ubuntu was the number of files.
I think on debian it takes a long time to make tags files in tags_dir because of a number of files.
Anyway this plugin seems to work well now.

I guess when using this plugin on linux system, gnu global should be built by a user anyway.

Thanks for your help and the great work.

**Comment by jsfaint** [comment]
> I guess when using this plugin on linux system, gnu global should be built by a user anyway.

In the original code, the gtags can be generated by `:GenGTAGS` in or `gtags` in terminal
And the GTAGS/GPATH/GRTAGS is stored in the root of repo directory.

But it is a little weird that ctags and gtags use different path to store the tags file.
So I changed the behavior, use the same folder for both ctags and gtags.

BTW: You can use auto-gen feature by set `let g:gen_tags#gtags_auto_gen = 1`, if the code belong to a git/hg/svn repo, the gtags will be generate and update automatically.

**Comment by coil398** [comment]
I got it, indeed as you mentioned, it's strange.
I understood your thought.

yes, exactly I'm using the feature now.
thank you.
