### ISSUE TITLE
GSYMS not delete by ClearGTAGS

### ISSUE THREAD

**Issue by fcying** [jsfaint/gen_tags.vim#28]
os:ubuntu 16.04
vim8

GenGTAGS
ClearGTAGS
GSYMS not delete.

:ClearGTAGS! can not run,  error log "E477: can not use '!' "

:ClearCtags! run normally

**Comment by jsfaint** [comment]
1. What is `GSYSMS`?
Never saw it before on other OS 😭 
Does global on Ubuntu different with other OS(windows, archlinux, macos)?

2. It's my bad I forget to add `-bang` in `command`, will fix it later

Thanks for the report

**Comment by fcying** [comment]
ubuntu16.04 default version use apt-get install: 
global --version
global - GNU GLOBAL 5.7.1
Copyright (c) 2008 Tama Communications Corporation
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
This is also commercial (for-profit) software based on BOKIN model.
Please see the donation page <http://www.gnu.org/software/global/donation.html>.

**Comment by jsfaint** [comment]
I search on google, and got this:
https://github.com/oseiler/global/blob/4ed65296dbe97432d0fec5d175682970f2657775/FAQ#L176

```
Q8. I can't make GSYMS file.
A8. No problem. GSYMS was merged into GRTAGS in GLOBAL-5.9 or later.
```
Oh.. Ubuntu still use the very old version of global

**Comment by jsfaint** [comment]
Fixed. Thanks for the report @fcying

**Comment by fcying** [comment]
It work fine now~~
