### ISSUE TITLE
Function name does not match script file name: gen_tags#mkdir

### ISSUE THREAD

**Issue by leihuxi** [jsfaint/gen_tags.vim#29]
I got below issue:
Error detected while processing /home/xileihu/.vim_runtime/plugged/gen_tags.vim/autoload/gen_tags/ctags.vim:
line   45:
E746: Function name does not match script file name: gen_tags#mkdir

vim version:
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Dec  8 2017 12:47:23)
Garbage after option argument: "-version"
More info with: "vim -h"

**Comment by jsfaint** [comment]
Oh.. I checked the source code, there are two `gen_tags#mkdir()` exist.
It's a bug caused by last refactoring.
I'll remove it later.

But the weird thing is, I can't reproduce the error on my side (windows and linux with vim8/neovim)

Thanks for the report

**Comment by jsfaint** [comment]
@leihuxi Can you have a try with latest code please?
Thanks

**Comment by leihuxi** [comment]
Perfect, thank you.

**Comment by jsfaint** [comment]
Thanks 😄
