### ISSUE TITLE
REQ: user event to load own key mapping

### ISSUE THREAD

**Issue by butterflyfish** [jsfaint/gen_tags.vim#32]
after tags are loaded, trigger user event, then user can add own key mapping.

for example, if language server is supported, 'gd' will map to related function.  in order to share the same key mapping, i hope this feature can be implemented.

https://github.com/autozimu/LanguageClient-neovim provide similar feature.

**Comment by jsfaint** [comment]
vim has built-in mapp for tag jumping `<C-]>` which means `Ctrl-]`

**Comment by butterflyfish** [comment]
@jsfaint i know. but i want to **map 'go to definition' to different interface based on plugin/filetype**. For c, when llvm/clang can not use, gen_tags is a good alternative, for language supported programming language, map to LanguageClient_textDocument_definition like
>     autocmd User LanguageClientStarted nnoremap <silent>  gd   :call LanguageClient_textDocument_definition()<CR>

**Comment by jsfaint** [comment]
You can map it in your vimrc, like this
```viml
autocmd FileType c,cpp nnoremap <silent> gd <C-]>
```

**Comment by butterflyfish** [comment]
if GTAGS loaded, map gd to <c-]>
if Language server is started, map gd to LanguageClient_textDocument_definition

for some projects e.g.  cross compiling, Language server can not use. then this plugin is a good alternative.

just want to know when GTAGS is loaded, and allow user to define own hooks.

**Comment by jsfaint** [comment]
If the GTAGS file exist, it will be loaded in `BufWinEnter` event.

```
autocmd BufWinEnter * call s:gtags_auto_load()
```

There is an ` augroup gen_gtags` for `gen_tags`, but I think it is not what you are looking for.

**Comment by butterflyfish** [comment]
please help implement interface that allow user to define its own key mapping after GTAGS are loaded.
thank you very much!

**Comment by jsfaint** [comment]
`gen_tags.vim` use vim built-in function for tag jumping.
There is no need to implement an interface to archive this job.

Everything you need is this map for the filetype that doesn't supported by the languageClient
```vim
autocmd FileType <filetype> nnoremap <silent> gd <C-]>
```

**Comment by butterflyfish** [comment]
would you like to merge patch below ?

```patch
diff --git a/autoload/gen_tags/gtags.vim b/autoload/gen_tags/gtags.vim
index 0a85523..6becaaf 100644
--- a/autoload/gen_tags/gtags.vim
+++ b/autoload/gen_tags/gtags.vim
@@ -15,6 +15,7 @@ function! s:gtags_add(file) abort
   if filereadable(a:file)
     let l:cmd = 'silent! cs add ' . a:file
     exec l:cmd
+    silent! doautocmd User GenTagsLoaded
   endif
 endfunction
```

example configuration in vimrc
```vim
augroup gtags
autocmd!
autocmd User GenTagsLoaded nnoremap gd <c-]>
autocmd User GenTagsLoaded nnoremap gr :cs find c <C-R>=expand('<cword>')<CR><CR>
augroup END
```

if mapping gd to ':cs find c <C-R>=expand('<cword>')<CR><CR>', I found it works only first time. open c file, gd can help jump to definition on function, use <c-o> to come back, gd does not work now.

**Comment by jsfaint** [comment]
Thanks for the reply, but I'm not sure if I understand your purpose correctly.

`s:gtags_add()` will be called in 2 conditions:
1. In `BufWinEnter` event
2. In callback function of `:GenGTAGS` command

And if the `GTAGS` file exist, it will be always loaded by `cs add`

So why do you need a event and run it multiple times for just repeat add the map?
Do you mean languageClient will overwrite it?

**Comment by butterflyfish** [comment]
The purpose is simple. I want to map one key map, like gd, to different action automatically. project use GTAGS, map one key to cscope action, while project use Language server(like cquery), map the same key to LanguageClient interface action. 

Based my understanding, GTAGS is only added once via BufWinEnter or :GenGTAGS, key map in augroup *gtags* are loaded one time also.

if anything is wrong, pls correct me.

**Comment by jsfaint** [comment]
This the document of `BufWinEnter` event.
```
							*BufWinEnter*
BufWinEnter			After a buffer is displayed in a window.  This
				can be when the buffer is loaded (after
				processing the modelines) or when a hidden
				buffer is displayed in a window (and is no
				longer hidden).
				Does not happen for |:split| without
				arguments, since you keep editing the same
				buffer, or ":split" with a file that's already
				open in a window, because it re-uses an
				existing buffer.  But it does happen for a
				":split" with the name of the current buffer,
				since it reloads that buffer.
```

----

I think it is a better solution for your case:
```viml
nnoremap gd <c-]>
nnoremap gr :cs find c <C-R>=expand('<cword>')<CR><CR>
autocmd Filetype <filetype supported by languageClient> nnoremap <buffer>  <silent>  gd  :call LanguageClient_textDocument_definition()<CR>
```

Set buffer-only map for the filetype supported by LanguageClient

**Comment by butterflyfish** [comment]
"autocmd !" help clear autocmd group, so I think it's acceptable for BufWinEnter.

some C project use gtags, some C project use Languager server(e.g. cquery). I just want to apply the same key map for gtags and language server protoocl. If project use cquery, i define keymap after Language client started event is issued.

```vim
autocmd User LanguageClientStarted nnoremap <silent>  gd   :call LanguageClient_textDocument_definition()<CR>
autocmd User GenTagsLoaded nnoremap gd <c-]>
```

**Comment by jsfaint** [comment]
OK, I think I get your point now.
It' OK to me for adding an event for User.

But I need to think about how to implement it.
As you know, `gen_tags.vim` support `ctags` and `gtags`, if I use same event in `ctags` and `gtags`, will cause the event triggered twice. That's not what we expected.

----
Just curious
I'm not familiar with `LanguageClient`, did the `LanguageClientStarted` event triggered multiple times?

**Comment by jsfaint** [comment]
@butterflyfish I added two events `GenTags#CtagsLoaded` and `GenTags#GtagsLoaded`

**Comment by butterflyfish** [comment]
@jsfaint , good job. thank you very much!

**Comment by jsfaint** [comment]
You're welcome 😄 
If the commit fit your requirement, please close the issue. thanks
