### ISSUE TITLE
Jumping to wrong path when `autochdir` is set

### ISSUE THREAD

**Issue by rawcoder** [jsfaint/gen_tags.vim#35]
Hi,

The tag jump (using C-]) doesn't work when [`autochdir`](https://vimhelp.appspot.com/options.txt.html#%27autochdir%27) option is set.

gen_tags seems to be using the directory in which neovim was invoked rather than the current directory.

**Comment by jsfaint** [comment]
It's limitation of vim built-in tag system, the path will be stored in the tag file.
I have no idea how to fix it yet.

**Comment by rawcoder** [comment]
But ctags seem to be working in this case.  Could it be because of gtags?

**Comment by jsfaint** [comment]
Yes, it's related to gtags, maybe I can try to fix it.
I already fix this issue partially before by adding `gen_tags#find_project_root()` function.

I just recalled this,  sorry for the wrong info above.

**Comment by jsfaint** [comment]
@rawcoder Can you verify branch `fix`, if it fix this issue? thanks

**Comment by rawcoder** [comment]
It's not working :(

For your reference here's the script I'm following:

```
#!/bin/bash
# create new prj dir and its subdirs
mkdir prj; cd prj; mkdir src include
# now create new file in include
pushd include; echo '#define FOOBAR(c) ({ c > 1 ? 20 : 10})' > test.h; popd
# similarly in src
pushd src; echo '#include "test.h"
int main() { return FOOBAR(1); }' > test.c; popd
# add to git (for defining prj root)
git init; git add -A; git commit -m 'init'
# now open vim and generate tags
vim src/test.c
# other test cases
# cd ..; vim prj/src/test.c
```

**Comment by jsfaint** [comment]
I reproduced your behavior with the code above.

I have a look at the help of `autochdir`
```
			*'autochdir'* *'acd'* *'noautochdir'* *'noacd'*
'autochdir' 'acd'	boolean (default off)
			global
			{only available when compiled with it, use
			exists("+autochdir") to check}
	When on, Vim will change the current working directory whenever you
	open a file, switch buffers, delete a buffer or open/close a window.
	It will change to the directory containing the file which was opened
	or selected.
	Note: When this option is on some plugins may not work.
```

It says
> Note: When this options is on some plugins may not work.

Do you know how did other plugin live with `autochdir`?

**Comment by jsfaint** [comment]
I searched on google, it looks `if_cscope` use relative path by default.
So I added `set nocscoperelative`, it works for me with your test example.
Can you have a try with `fix` branch?

Thanks

**Comment by rawcoder** [comment]
It is working in some cases but, unfortunately, failing in others.

Here's a test case for which it is failing:
```
# Working dir is prj
cd include
vim ../src/test.c
# now try tag-jump
```

**Comment by jsfaint** [comment]
Hey @rawcoder , sorry for the long wait.
I fixed this issue in branch `fix`, can you have a try?

**Comment by rawcoder** [comment]
Thanks, it works!

But now I am facing another issue.  If `gtags_auto_gen` is set to 1, then I am unable to exit nvim with `:q`.  I have to use `C-c` for forcing exit.
After setting `verbose` and `statusline` to 1, I am getting the 'Generating tags in background, please stand by...' message which goes away after a tag jump with the message 'The same job is still running'.

Here's a script for reproducing the issue:
```
#!/bin/bash

# /!\
# make sure 'g:gen_tags#gtags_auto_gen' is set to 1 in init.vim

# create new demo dir and its subdirs
mkdir demo; cd demo; mkdir src include
# now create new file in include
pushd include; echo '#define FOOBAR(c) ({ c > 1 ? 20 : 10})' > test.h; popd
# similarly in src
pushd src; echo '#include "test.h"
int main() { return FOOBAR(1); }' > test.c; popd
# add to git (for defining project root)
git init; git add -A; git commit -m 'init'
# now open the file in vim and do a tag-jump on 'FOOBAR'
vim src/test.c
# quit vim and re-open
vim src/test.c
# try quitting vim with ':q'
```
The "window" does disappear but control is not transferred back to shell;  a `C-c` is required.

**Comment by jsfaint** [comment]
That's weird.
I can't reproduce it.
Here is my screen record
[![asciicast](https://asciinema.org/a/fRglbTEYazL7H4UTF33wzos2O.png)](https://asciinema.org/a/fRglbTEYazL7H4UTF33wzos2O)

**Comment by rawcoder** [comment]
Hmm, check out [this](https://asciinema.org/a/3rwTxE7opsEdbbYmizDmTjFqj)

**Comment by jsfaint** [comment]
Can you show your vimrc?
It will be appreciated if you remove the unnecessary config in vimrc

**Comment by rawcoder** [comment]
Here's a minimal vimrc with which I am able to reproduce the issue:
```
" ---------- vim-plug settings ----------

call plug#begin('~/.config/nvim/bundle')
Plug 'jsfaint/gen_tags.vim'
call plug#end()


" ---------- gen-tags settings ----------

let g:gen_tags#gtags_auto_gen = 1
"let g:gen_tags#ctags_prune = 0                     " prune tags by default
let g:gen_tags#verbose = 1
let g:gen_tags#statusline = 1
```

**Comment by jsfaint** [comment]
I still can't reproduce it with your vimrc.
I will show some message because of verbose is enabled, but only enter key required.
There is no need to press `Ctrl-c`

Which vim or neovim version do you use?
I use neovim v0.3.0 on archlinux

**Comment by jsfaint** [comment]
Screen record with your vimrc
[![asciicast](https://asciinema.org/a/5ZL0U8EghyfawzXB78AhZuC8P.png)](https://asciinema.org/a/5ZL0U8EghyfawzXB78AhZuC8P)

**Comment by rawcoder** [comment]
I guess I have figured it out.

I am using v0.2.2.  When I test the same on v0.3.0, it works.

I think [this issue](https://github.com/neovim/neovim/issues/6530) in neovim repo is relevant.

**Comment by rawcoder** [comment]
Thank you for your help.  I guess we can close this issue now.
