### ISSUE TITLE
Potential usability issue (Dont suppress gtags errors)

### ISSUE THREAD

**Issue by joereynolds** [jsfaint/gen_tags.vim#37]
if you try and do `gtags` in a file that you do not have access to, the whole indexing of tags fails.

For example, I had a `.log` file owned by `root` which I couldn't read.
`gen_tags` would generate empty `GTAGS` `GPATH` and `GRTAGS` files.
I realise this is a `gtags` problem and nothing to do with `gen_tags` but thought I would flag it up.

When you manually call `gtags` in a project, at least the error comes through. gen_tags seems to be suppressing the error (Does this happen with `g:gen_tags#verbose = 1`?).

I will try and post a way to replicate soon.

Thanks!

**Comment by jsfaint** [comment]
The return code and output is not handled currently.
If we need this feature, I need to rewrite job control part.

**Comment by jsfaint** [comment]
Sorry for the wrong message above.
I just checked the source code. this feature is implemented already.
```vim
function! s:job_stdout(job_id, data, ...) abort
  if type(a:data) == 1 "string
    call gen_tags#echo(a:data)
  elseif type(a:data) == 3 "list
    for l:item in a:data
      call gen_tags#echo(l:item)
    endfor
  endif
endfunction
```

But you need write this in vimrc to enable it.
```
let g:gen_tags#verbose = 1
```

**Comment by jsfaint** [comment]
@joereynolds Can you help to check if the current implementation working for this issue, please?
Thanks~

**Comment by jsfaint** [comment]
@joereynolds ping~

**Comment by joereynolds** [comment]
Hey jsfaint,

I haven't gotten round to replicating the issue but the next time it happens I'll set the verbose option and let you know.

Thanks!

**Comment by jsfaint** [comment]
@joereynolds Roger that, thanks!
