### ISSUE TITLE
Question... Every time I go in Vim and load a project I have to do :GenCtags?

### ISSUE THREAD

**Issue by staycreativedesign** [jsfaint/gen_tags.vim#38]
Silly question Im loading up a project lets say ~/Projects/foo then I do ```:GenCTAGS``` great everything is working now I close vim and goto the same project the tags arent saved? Is it because its in a tmp dir?

**Comment by staycreativedesign** [comment]
Even better I've set
```let g:gen_tags#use_cache_dir = 0```
so it creates a ```.git/tags_dir/prj_tags

But it cant find the tags in that folder
when I set it to ```1``` it can now find the tags?!

**Comment by jsfaint** [comment]
By default `g:gen_tags#use_cache_dir` is 1, the tag file is under `$HOME/.cache/tag_dirs`

I'm not sure if your project is git based or not.
The option `g:gen_tags#use_cache_dir` only effect the project that managed by `git/svn/hg`.

**Comment by jsfaint** [comment]
@staycreativedesign Any update?

**Comment by jsfaint** [comment]
Since there is no update for almost 2 months. Close it.
If you have any question please feel free to reopen this issue, thanks
