### ISSUE TITLE
ClearCtags won't remove the tag's folder

### ISSUE THREAD

**Issue by fcying** [jsfaint/gen_tags.vim#4]
only remove the prj_tags file.

**Comment by jsfaint** [comment]
Sorry, the `delete()` function provide in vimscript can only delete files.
The folder can't remove by only call vimscript.
I wanna use this plugin in multi-platform like Windows, Linux and macOS.
So this issue will not be fixed until I find a better choice.

**Comment by fcying** [comment]
I try to use delete(l:file,"rf"), it was run ok in Windows.
  let l:file = expand(s:get_project_ctags_dir())
  let l:file = s:fix_path_for_windows(l:file)
  call delete(l:file,"rf")

**Comment by jsfaint** [comment]
@fcymk2 I tried `delete()` with flags, it works on linux and osx too. Thanks. 👍 

There is another problem about the behavior of ClearCtags command.
When the `ext.conf` file exist, shall we remove `ext.conf` with folder? Or only remove the folder when the `ext.conf` not exist?

Maybe just delete all the thing including the folder 😆

**Comment by fcying** [comment]
if you won't remove ext.conf, you can delete the folder separately by use flag "d", use this flag only delete folder when it's empty

**Comment by jsfaint** [comment]
`ClearCtags` will delete everything include the folder for now, unless we add another command for deleting the ext.conf file.
I'm a little busy now and will add it later.

BTW: PR is appreciated :smile:
