### ISSUE TITLE
Disable Update GTags in the background message

### ISSUE THREAD

**Issue by Govinda-Fichtner** [jsfaint/gen_tags.vim#41]
After enabling autoupdate for gtags everytime I open a file with vim I get the "Update Gtags in the background" message AND I have to acknowledge it by hitting <enter>. Only then can I work on the file.

Is there a way to disable the message and the need to hit <enter>?

**Comment by jsfaint** [comment]
Did you set `g:gen_tags#verbose = 1` in your vimrc?
Please remove it. 😄

**Comment by Govinda-Fichtner** [comment]
Well, I thought I removed it, but there was a similar config from another tags plugin present that I tested. Sorry for the noise!

**Comment by jsfaint** [comment]
Can I ask which plugin has similar config? Just curious 😀
