### ISSUE TITLE
How to check that the nvim-completion-manager integration works with gtags

### ISSUE THREAD

**Issue by Govinda-Fichtner** [jsfaint/gen_tags.vim#42]
I have gen_tags running successfully. I also have ctags and gtags files in `$HOME/.cache/tag_dirs`.

How can I check now that the advanced capabilities of gtags are working. What kind of commands can I use in vim to see my configuration is correct?

**Comment by jsfaint** [comment]
The ncm gtags source is out-of-box.
If you installed ncm correctly, it should be work then.
I read the doc of ncm, maybe you can refer the link below
https://github.com/roxma/nvim-completion-manager/blob/master/doc/nvim-completion-manager.txt#L773

**Comment by Govinda-Fichtner** [comment]
OK. I just noticed that ncm is not maintained any more. So I am thinking about moving to deoplete... how about there?

**Comment by jsfaint** [comment]
It's out-of-box too, but I don't know how to check the enabled source.
Maybe you can enable deoplete logging and check the log file
```vim
let g:deoplete#enable_profile = 1
call deoplete#enable_logging('DEBUG', 'd:\deoplete.log')
```

Sorry

**Comment by Govinda-Fichtner** [comment]
While enabling this my deoplete autocompletion stopped working. After removing these lines it started to work again. But I noticed that deoplete does show the source of the completion and I had entries with gtags. So I suppose it works. Thanks for you help!

**Comment by jsfaint** [comment]
😀 You're welcome
