### ISSUE TITLE
[feature request] Add an option to detect if tags exist for auto_gen

### ISSUE THREAD

**Issue by fcying** [jsfaint/gen_tags.vim#47]
If have already generated a tag, it will automatically update, else not auto_gen

**Comment by jsfaint** [comment]
The auto-update will be done in background after the files were modified.
Why do you need an option for it? Do you want to disable auto-update?

**Comment by fcying** [comment]
I have some project, only C++ project need tags and auto_gen. 
If I enable auto_gen, it will gen tags in all project. 
So i want check the tags file at first,  if exist(has been manually run gen_tag), auto_gen, else disable auto_gen.

**Comment by jsfaint** [comment]
Maybe you can disable auto_gen by using local vimrc (per project).
vim has built-in support, it can be enabled by
```vim
set exrc
set secure
```

There are also some plugins can do this job.
Like https://github.com/embear/vim-localvimrc

For myself, the auto gen feature was disabled always, I generate tag by hands (only once), then it will update automatically.

**Comment by fcying** [comment]
just enable auto_gen in C++project, it can work now, thanks
```
let s:vimconf_path = findfile(".vimconf", ".;")
if s:vimconf_path != ""
    exec 'source ' . s:vimconf_path
endif
```
.vimconf in project root dir
```
    let g:gen_tags#gtags_auto_gen = 1
    let g:gen_tags#ctags_auto_gen = 1
```

**Comment by fcying** [comment]
use event work perfect, not need project config.

if my project need tag, run `<leader>tg` once, and then it can auto gen.  

```
    nnoremap <leader>tg :GenCtags<CR>:GenGTAGS<CR>:echo "gen tags end"<CR>
    nnoremap <leader>tc :ClearCtags<CR>:ClearGTAGS!<CR>:echo "clear tags end"<CR>

    autocmd User GenTags#CtagsLoaded let g:gen_tags#ctags_auto_gen = 1
    autocmd User GenTags#GtagsLoaded let g:gen_tags#gtags_auto_gen = 1

    let g:gen_tags#ctags_auto_gen = 0
    let g:gen_tags#gtags_auto_gen = 0
```
