### ISSUE TITLE
Remove default Ctrl+\ mappings (or make optional)

### ISSUE THREAD

**Issue by rslindee** [jsfaint/gen_tags.vim#48]
I think the default-provided Ctrl+\ mappings for cscope hotkeys are a great inspiration, but defaulting them to being enabled might be a little intrusive for some (e.g. those who already have Ctrl+\ combinations mapped).

In my opinion, making said mappings optional (via something like g:gen_tags#gtags_mappings) or, even better, removing them entirely and providing instructions/examples on how to add said mappings to a user's .vimrc in the documentation would be ideal. Doing so would really help make this plugin more clean/orthogonal.

If you think this is worth pursuing but don't have the time, just let me know and I could try introducing a pull request with said changes.

Keep up the great work, by the way! I'm really liking this plugin.

**Comment by jsfaint** [comment]
Thanks for your great affirmation 😄 

This plugin was started from my personal vimrc
As you say, it is intrusive for someone else. I was thinking to change it long time ago.

The mapping was inspired from [cscope_maps.vim](http://cscope.sourceforge.net/cscope_maps.vim), after several years the maps becomes some kind of muscle memory for me.
I'm a little afraid that if I remove the default mapping will make the old user unhappy.

Maybe I can just add an option to disable the default mapping. And it will enabled by default, if anyone want to disable it, they can just set the option to `0`.

Thanks for your advice 👍

**Comment by jsfaint** [comment]
I added an option `g:gen_tags#gtags_default_map` for this issue. @rslindee

**Comment by rslindee** [comment]
Sounds great! I really appreciate your quick turnaround with this.
