### ISSUE TITLE
Autogenerate GTAGS file upon opening a file in a GIT or HG project

### ISSUE THREAD

**Issue by Mariappan** [jsfaint/gen_tags.vim#5]
I am currently using guten-tags plugin which will create tags file on its own when i open a file and update the tags file if i edit it.
Today I found your plugin which supports GTAGS also and I am trying to use it.
But the GTAGS file is not auto generated as of now. 
Is there a plan to make the GTAGS file auto generate on opening a file in a project.

**Comment by jsfaint** [comment]
Hey @Mariappan thanks for your feedback :)
I'll have a look on gunten-tags.

Maybe I can add an option to enable/disable auto generate feature?
By now, you only need to run `:GenGTAGS` once, then the database will be updated on file saving automatically.

For hg support, I have no plan to support it yet, because I don't use hg, and to support it I need to rewrite this function `gen_tags#find_project_root()`

**Comment by jsfaint** [comment]
Hi @Mariappan , could you have a try with the latest code to see if it fit for you?

The auto gen feature was disabled by default, you need to set `g:gen_tags#ctags_auto_gen` and `g:gen_tags#gtags_auto_gen` in your vimrc

```viml
let g:gen_tags#ctags_auto_gen = 1
let g:gen_tags#gtags_auto_gen = 1
```

**Comment by Mariappan** [comment]
Thanks @jsfaint . That was some quick resolution.

I added the following in my nvim init.vim file
+ let g:gen_tags#ctags_auto_gen = 1                                                                   
+ let g:gen_tags#gtags_auto_gen = 1    

When I open a file in git repo using vim .4.1689, it is printing like this
"moveresize.c" 64L, 1609CGenerate GTAGS in [Background]Generate GTAGS in [Background]
But the tags file is not generated.

When i open the file in neovim 0.1.7 I am getting the following error:
"moveresize.c" 64L, 1609C                                                                                                                                                                                                                                                         
Error detected while processing function AutoGenGtags[13]..<SNR>32_Gtags_db_gen:                                                                                                                                                                                                  
line   33:                                                                                                                                                                                                                                                                        
E127: Cannot redefine function <SNR>32_gtags_db_gen_done: It is in use                                                                                                                                                                                                            
Error detected while processing function <SNR>32_gtags_db_gen_done:                                                                                                                                                                                                               
line    1:                                                                                                                                                                                                                                                                        
E121: Undefined variable: b:bak                                                                                                                                                                                                                                                   
Error detected while processing function <SNR>32_gtags_db_gen_done:                                                                                                                                                                                                               
line    1:                                                                                                                                                                                                                                                                        
E116: Invalid arguments for function <SNR>32_Restore_cwd                                                                                                                                                                                                                          
Error detected while processing function <SNR>32_gtags_db_gen_done:                                                                                                                                                                                                               
line    3:                                                                                                                                                                                                                                                                        
E121: Undefined variable: b:file                                                                                                                                                                                                                                                  
Error detected while processing function <SNR>32_gtags_db_gen_done:                                                                                                                                                                                                               
line    3:                                                                                                                                                                                                                                                                        
E116: Invalid arguments for function <SNR>32_add_gtags                                                                                                                                                                                                                            
Error detected while processing function <SNR>32_gtags_db_gen_done:                                                                                                                                                                                                               
line    4:                                                                                                                                                                                                                                                                        
E108: No such variable: "b:file"                                                                                                                                                                                                                                                  
Error detected while processing function <SNR>32_gtags_db_gen_done:                                                                                                                                                                                                               
line    5:                                                                                                                                                                                                                                                                        
E108: No such variable: "b:bak"                                                                                                                                                                                                                                                   
Press ENTER or type command to continue

**Comment by jsfaint** [comment]
@Mariappan Sorry, I'm an idiot, I made a typo in function name. which cause ctags autogen function not work.
I checked in vim 8.0,329, it works now.
For neovim support, I'll check it later.

Thank you for your feedback. 👍

**Comment by jsfaint** [comment]
@Mariappan I checked nvim 0.1.7 with latest code looks good to me.
Can you try again with the latest code? Thanks!

**Comment by Mariappan** [comment]
Sorry @jsfaint Still i didnt have luck.
I have set the auto_gen variable in vimrc and tried to open one c in a git repo.
Please find the logs:

pon@pon-ubuntu:~/github/dwm$ tail ~/.vimrc
catch
colorscheme koehler
endtry

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
let g:chromatica#libclang_path='$HOME/.linuxbrew/lib'

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
let g:gen_tags#ctags_auto_gen = 1
let g:gen_tags#gtags_auto_gen = 1
pon@pon-ubuntu:/github/dwm$
pon@pon-ubuntu:/github/dwm$ ls
BUGS config.h drw.c dwm.1 dwm.png LICENSE moveresize.c README TODO util.c
config.def.h config.mk drw.h dwm.c dwmstatus.c Makefile movestack.c shiftview.c transient.c util.h
pon@pon-ubuntu:/github/dwm$ nvim dwm.
pon@pon-ubuntu:/github/dwm$ nvim dwm.c
pon@pon-ubuntu:/github/dwm$ ls
BUGS config.h drw.c dwm.1 dwm.png LICENSE moveresize.c README TODO util.c
config.def.h config.mk drw.h dwm.c dwmstatus.c Makefile movestack.c shiftview.c transient.c util.h
pon@pon-ubuntu:/github/dwm$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
pon@pon-ubuntu:/github/dwm$ nvim dwm.c
pon@pon-ubuntu:/github/dwm$ ls
BUGS config.h drw.c dwm.1 dwm.png LICENSE moveresize.c README TODO util.c
config.def.h config.mk drw.h dwm.c dwmstatus.c Makefile movestack.c shiftview.c transient.c util.h

**Comment by jsfaint** [comment]
@Mariappan 😢 Can you do me a favor for the following information? Thanks

1. Can I tell me which version of ubuntu you use?
2. Which version of vim you use, and does it works on vim (not neovim) now?
3. According to the log above, you're testing with neovim, right?
Please tell me the result of these commands after you open dwm.c under folder dwm

```viml
echo g:gen_tags#project_root
echo getcwd()
echo g:gen_tags#ctags_auto_gen
echo g:gen_tags#ctags_auto_gen
```

**Comment by jsfaint** [comment]
@Mariappan My environment is Archlinux + neovim 0.1.7
Everything works as the expect.
[![asciicast](https://asciinema.org/a/3pg5gd6qlo9yx5wrpdh0j50ve.png)](https://asciinema.org/a/3pg5gd6qlo9yx5wrpdh0j50ve)

**Comment by Mariappan** [comment]
Oops my bad, it was working, I have commented the plugin.
Closing the issue. Thanks a lot for your quicker response.

**Comment by jsfaint** [comment]
@Mariappan 😄 Thanks for your help and feedback.
