### ISSUE TITLE
if HOME path contain backspace on windows, it doesn't work

### ISSUE THREAD

**Issue by czlhs** [jsfaint/gen_tags.vim#51]
change the tagdir  in gen_tags.vim solved it,
```
let l:tagdir = 'c:/porg/cache/' . gen_tags#get_db_name(l:root)
```

**Comment by jsfaint** [comment]
Sorry, I didn't get your point.
Could you give some more description, please?

**Comment by jsfaint** [comment]
Do you mean the tagdir which includes space? @czlhs
