### ISSUE TITLE
ctags can't add g:gen_tags#ctags_opts parameter , it would pop "-f option may not follow a file name"

### ISSUE THREAD

**Issue by maxtcy** [jsfaint/gen_tags.vim#56]
Hi Sir, 

gen_tags.vim version is 
![image](https://user-images.githubusercontent.com/7471380/41339291-0573e2d8-6f27-11e8-9ff9-0d9f1105f1c5.png)
It shoud be the latest one. 

If add `g:gen_tags#ctags_opts` in my vimrc, it would pop up `ctags: -f option may not follow a file name`
Message as below 
![test](https://user-images.githubusercontent.com/7471380/41339571-c3c41280-6f27-11e8-910f-f86ba4d831ad.png)

As comparison, **Remove** `g:gen_tags#ctags_opts`  in vimrc , there is no such message popup. 

Right now, i am **remove it** as workaround. 
Since there is **no such issue** in previous version. 
Can you take a look ?

**Comment by jsfaint** [comment]
I can't reproduce on both windows and linux.
![image](https://user-images.githubusercontent.com/571829/41340525-2f3b9e46-6f2a-11e8-91db-355d1c84a35c.png)

![image](https://user-images.githubusercontent.com/571829/41340778-bee38248-6f2a-11e8-9d07-e277a3fb1eb0.png)

**Comment by maxtcy** [comment]
How should i do to provide more information for you about this problem?

**Comment by jsfaint** [comment]
Please provides the following information:
1. vim version, ctags version
2. value of  `g:gen_tags#ctags_opts`
3. Run ctags command directly with the parameters on your image

**Comment by maxtcy** [comment]
1.
 vim version 
![image](https://user-images.githubusercontent.com/7471380/41342913-e8265f4a-6f2f-11e8-965f-33645e2909f1.png)
ctags version
![image](https://user-images.githubusercontent.com/7471380/41342951-fcd7e0f8-6f2f-11e8-918b-303078384d1a.png)

2. value of `g:gen_tags#ctags_opts`
![image](https://user-images.githubusercontent.com/7471380/41343023-2876490c-6f30-11e8-9b83-0316786ac1f2.png)

3. Not quite sure about the answer of it. 
Do you mean "keyin what i see popup message in the root folder " ?
![test](https://user-images.githubusercontent.com/7471380/41339571-c3c41280-6f27-11e8-910f-f86ba4d831ad.png)
ex:` $ctags --extras=+r --fields=+niazS -f /folder_path/.git/tags_dir/prj_tags -R /folder_path`
Do you mean this way ? **If yes**, it seems like i manually keyin these command , it **can** generate the prj_tags  out.

THX

**Comment by jsfaint** [comment]
I reproduced it with vim 8.1, but neovim 0.3.0 works well.
That's weird.

**Comment by jsfaint** [comment]
And when I modified your `g:gen_tags#ctags_opts` setting.
Modify `let g:gen_tags#ctags_opts = ' --fields=+niazS'` to `let g:gen_tags#ctags_opts = '--fields=+niazS'`
Just remove the space before `--fields`

It works... WTF

**Comment by maxtcy** [comment]
Hi Sir, 
how about **multiple** `g:gen_tags#ctags_opts`
As you can see, there are several opts marked out in my setting. 
If i would like to use more than 1 opts, Is my setting correct ?
THX

**Comment by jsfaint** [comment]
I'm not sure the meaning of multiple `g:gen_tags#ctags_opts`.
Can you explain?

**Comment by maxtcy** [comment]
As screen-shot show in the below , only `--fields=+niazS` , there are **5 opts more** , i just **marked out**.
![image](https://user-images.githubusercontent.com/7471380/41343023-2876490c-6f30-11e8-9b83-0316786ac1f2.png)

**Comment by jsfaint** [comment]
Your setting is correct.
But as I said above, vim has some issues to support your first line.
You need to remove the **space** before `--fields`

**Comment by maxtcy** [comment]
Hi Sir, 
Can you hlep me try it with all my setting? 

Since i still encounter some error, but if i key in in command in the terminal. 
There is no such error. 

If save file, it would pop up below error in my side.
ctags: Warning: Unsupported parameter ' ' for "fields" option
ctags: Warning: Unsupported parameter '=' for "fields" option
ctags: Warning: Unsupported parameter 'q' for "fields" option
ctags: Warning: Unsupported parameter ' ' for "fields" option
ctags: Warning: Unsupported parameter 'c' for "fields" option
ctags: Warning: Unsupported parameter 'd' for "fields" option
ctags: Warning: Unsupported parameter '=' for "fields" option
ctags: Warning: Unsupported parameter ' ' for "fields" option
ctags: Warning: Unsupported parameter 'c' for "fields" option
ctags: Warning: Unsupported parameter 'd' for "fields" option
ctags: Warning: Unsupported parameter '=' for "fields" option

**Comment by jsfaint** [comment]
I tried all your ctags_opts yesterday, but it works for me.
![image](https://user-images.githubusercontent.com/571829/41386045-f0933a68-6fb1-11e8-8e73-845fb22bdbe9.png)
![image](https://user-images.githubusercontent.com/571829/41386064-21585c8c-6fb2-11e8-886b-137e89a9ad57.png)

**Comment by jsfaint** [comment]
@maxtcy I refactor this part for better compatibility.
Please try the latest code. Thanks

**Comment by maxtcy** [comment]
Will try it later. Stack in the middle of something

Jia Sui <notifications@github.com> 於 2018年6月14日 週四 上午11:01寫道：

**Comment by maxtcy** [comment]
Hi Sir, 

Thanks for your support to refactor. There is no problem after test it. 
Both string and list are working fine. 

Thanks ,

**Comment by jsfaint** [comment]
Thanks for your contribution to make `gen_tags.vim` better 👍
