### ISSUE TITLE
[question] Can I use Gtags for jump instead of ctags?

### ISSUE THREAD

**Issue by fcying** [jsfaint/gen_tags.vim#59]
I test follow script, but not work
```
set cscopetag
set cscopeprg='gtags-cscope'
```

**Comment by jsfaint** [comment]
It's already set in gen_tags.vim
https://github.com/jsfaint/gen_tags.vim/blob/e79c4af80cf77231949a03c2fcaa86f29c5df879/autoload/gen_tags/gtags.vim#L145-L146

It the GTAGS exists， `ctrl-]` jumps with GTAGS, if the tag can not be found, it will fallback to ctags

**Comment by fcying** [comment]
it not work, `E257: cstag: tag not found`
GTAGS is exist, `Ctrl+\ c` can work.
If I GenCtags, it can jump.

**Comment by jsfaint** [comment]
That's because some file that gtags can't generate definition for it.
Which cause this issue, it's upstream issue, not issue in `gen_tags.vim`

`ctrl+\ c` works, that's because
```
Ctrl+\ c    Find functions calling this function
```

You should try, it should not work too
```
Ctrl+\ g    Find this definition
```

**Comment by fcying** [comment]
Ok, I understand. this is still a bit of a hassle, ctags still needs to be generated for jump(`c-]`), thanks for reply

**Comment by jsfaint** [comment]
You can use universal-ctags or pygments as the backend of gtags to generate the tags.
But it looks universal-ctags and pygments don't support caller or reference querying.
