### ISSUE TITLE
How could i disable gtags

### ISSUE THREAD

**Issue by mikezaby** [jsfaint/gen_tags.vim#6]
I want to disable gtags because I don't use them and it promps every time I open the neovim a message about missing GNU Global

**Comment by jsfaint** [comment]
Thanks for your feedback 😄 
I add two options for this feature.

Please add this into your vimrc to disable gtags support

```viml
let g:loaded_gentags#gtags = 1
```

**Comment by mikezaby** [comment]
Thanks for the fast response :smile:

**Comment by jsfaint** [comment]
@mikezaby Thanks for using 😄 
Please feel free to shot another issue, if you have any other questions
