### ISSUE TITLE
[feature request] support ncm2 source

### ISSUE THREAD

**Issue by fcying** [jsfaint/gen_tags.vim#61]
https://github.com/ncm2/ncm2

nvim-completion-manager is not maintained.

**Comment by jsfaint** [comment]
I don't have time to do this job currently.
Maybe later

**Comment by fcying** [comment]
I add a commit to add ncm2 source 0b89c5fc80568dc9ba7543398e955ed209f390b9
I don't know why I can't send a pr separately, it is mixed with the previous pr@_@ #62

**Comment by jsfaint** [comment]
You need to commit ncm source in another branch, then push it, and create a new PR.
