### ISSUE TITLE
Increase Python 3's priority.

### ISSUE THREAD

**Issue by kashewnuts** [jsfaint/gen_tags.vim#70]
# Problems summary

The Python interface will be evaluated before the Python 3 interface

## Expected

The Python *3* interface will be evaluated before the Python interface.
Because Python 2 will be EOL to 2020, there is no reason to give priority over Python 3.

## Environment Information (Required!)

 * OS: macOS Sierra
 * Vim version: 8.0.1633 https://github.com/splhack/macvim-kaoriya/releases/tag/20180324
 * ctags/gtags: Installed Ctags, but not installed gtangs

 ```
 $ vim --version | grep python
 +cscope            +linebreak         +python/dyn        +vreplace
 +cursorbind        +lispindent        +python3/dyn       +wildignore
 ```

## Provide a minimal init.vim with less than 50 lines

```vim
call plug#begin('~/.cache/plugged')
Plug 'jsfaint/gen_tags.vim'
call plug#end()

let g:loaded_gentags#gtags = 1  " gtags is irrelevant, it is off.
```

## How to reproduce problems from vim startup

 1. `$ vim test.py`
 2. Run `:python3 print('hello')` in Vim's command line mode.
 3. Error!

```
E837: このVimでは :python を使った後に :py3 を使えません
E263: このコマンドは無効です,ごめんなさい: Pythonライブラリをロードできませんでした.
```

**Comment by jsfaint** [comment]
The #71 was merged already, close this issue for good.
Thanks

**Comment by kashewnuts** [comment]
Thanks for merged!
