### ISSUE TITLE
关于结果很多的时候

### ISSUE THREAD

**Issue by ghost** [jsfaint/gen_tags.vim#72]
我在知乎上看到了你的回答,所以直接用中文进行提问咯,结果很多的时候会占据很多屏幕空间(这个应该是我没设置),而且还要全部看完才能选择,能不能改善以下选择的方式,可以用光标进行选择,增加预览功能就更好了.啊哈

**Comment by jsfaint** [comment]
Please refer this #49 
```
set cscopequickfix=s+,c+,d+,i+,t+,e+,a+
```

**Comment by ghost** [comment]
谢谢,没想到回复这么快,非常感谢

**Comment by jsfaint** [comment]
@garytone 跳转这部分用的是vim内置的功能，可以通过`set cscopequickfix`来改成显示在quickfix
但是如果要做到像ctrlp或者fzf那样的效果就需要额外的工作了，有点得不偿失因为没法和内置的jump list一起协作，也就是没法用ctrl-t跳回来
之后可以考虑加一个依赖fzf的命令来实现类似的功能，但是使用内置功能应该是最高效的做法了

**Comment by ghost** [comment]
ok,感谢,真是麻烦你了
