### ISSUE TITLE
add option to use only ctags

### ISSUE THREAD

**Issue by jahanbani** [jsfaint/gen_tags.vim#75]
I just installed the plugin on Windows and I get error that gtag doesn't exist

`GNU Global not found
gen_gtags.vim need GNU Global`

However, I would like to just use ctags and not gtags. I have portable ctags and added to path variable. Am I doing something wrong or maybe this is an option that can be added.

Thank you

**Comment by jsfaint** [comment]
There is an option `g:loaded_gentags#gtags`, please refer the help docs in vim

**Comment by jahanbani** [comment]
Thank you very much. Solved 🥇
