### ISSUE TITLE
Auto generate ctags file

### ISSUE THREAD

**Issue by ahmedelgabri** [jsfaint/gen_tags.vim#8]
I'm trying out this plugin that looks exactly like what I need, I like its simplicity a lot. But I'm a bit struggling to get it work properly. Here is my setup

```vim
let g:loaded_gentags#gtags = 1
let g:gen_tags#ctags_auto_gen = 1
let g:gen_tags#verbose = 1
```
When I open a file I get the message that it's working & generating tags for the project 

```
CGenerate project ctags database in [Background]
```

But I can't find the `tags` file anywhere, not the root of the project & not inside `~/.cache/tags_dir/<project_path>`? 

Although `set tags` shows that there is a file here `~/.cache/tags_dir/<project_path>/prj_tags` but when I `ls` inside the folder, it's empty.

**Comment by jsfaint** [comment]
I'm sorry to hear that the plugin not work out-of-box for you.
Can you provide more info about this issue, please?
Like your platform, vim version and your codebase size.

ctags generate tagfile is a bit slow for the large codebase.
The plugin will set run `set tags` first, then generate tagfile in background (to avoid vim hang).
you can't get any tagfile, before the generator finish its job.
I'll also try to reproduce this issue on my side.

Sorry for the inconvience

EDIT:
One more thing, auto generate feature **only** works in git repository.
If your code are not git repository, You need to run `:GenCtags` once.
But it's hard to find the project root, if it is not in a git repository.
gen_tags.vim use `CWD` currently.. So you need to make sure your `CWD` for a project is always same.

**Comment by ahmedelgabri** [comment]
I'm already in a git repo, I know about that :)

Here more info:

- neovim HEAD `NVIM v0.2.1-331-g6650588c`
- macOS Sierra 12.10.5
- codebase is around 8k files 

> ctags generate tagfile is a bit slow for the large codebase.

Currently I'm using vim-gutentags & it's actually not slow.

**Comment by jsfaint** [comment]
8k files shouldn't be problem here, large codebase I mean like linux kernel 😄 

Can you run `:echo gen_tags#find_project_root()` and tell me the result, please?
The result should be your git repository root.

There is a known issue in VimR (neovim GUI for macOS), it will get the wrong CWD which cause `gen_tags.vim` can't work as expect.

And another action I need your help, as you open neovim, please open another terminal and run `ps aux | grep ctags'` to check if `gen_tags.vim` execute ctags correctly.

Thank you~

**Comment by ahmedelgabri** [comment]
I'm using neovim in the terminal not the GUI

- `:echo gen_tags#find_project_root()` returns the right root
- `ps aux | grep ctags` doesn't show `ctags` running

**Comment by jsfaint** [comment]
That's weird.. I already checked on my windows and linux environment,  everything works well. I'll check it on my mac later.

If you run this command by manual, does it report any problem?
```bash
ctags -f <tagfile name> -R <project root>
```
And also what's the result of this command?
```
ls -l ~/.cache/tags_dir/
```

Thanks

**Comment by ahmedelgabri** [comment]
I had a problem with `ctags` fixed that & will see now if it works or not, will monitor for a couple of days & let you know. Thanks for the help! 😊

**Comment by jsfaint** [comment]
@ahmedelgabri Good to know~ I wish you enjoy this plugin.
Wait for the updates 👍 
Thank you~

**Comment by ahmedelgabri** [comment]
Looks like everything is working great 👍 

I have only one minor issue but I guess it's more `ctags` related than your plugin, which is that `ctags` when it runs it maxes out my CPU, any tips on how to debug/fix this or is this normal? 

<img width="981" alt="" src="https://cloud.githubusercontent.com/assets/63876/26520791/977cebb4-42d9-11e7-8ed6-d833e312e86f.png">

**Comment by jsfaint** [comment]
I'm on vacation now, will check it later.
I installed ctags via homebrew. Where did you get it?

**Comment by ahmedelgabri** [comment]
Yes through homebrew, I using [`universal-ctags`](https://github.com/universal-ctags/ctags)

**Comment by jsfaint** [comment]
@ahmedelgabri I checked on my mac and `ctags` eat up the CPU too.
![image](https://user-images.githubusercontent.com/571829/27430732-43b29f62-577c-11e7-9381-cd6ae6ea8c82.png)
So I think it's normal :)

**Comment by ahmedelgabri** [comment]
Ok, so nothing can be done then :)

Thanks for the help!
