### ISSUE TITLE
g:gen_tags#use_cache_dir creates useless directories when used with vim-fugitive

### ISSUE THREAD

**Issue by ian-howell** [jsfaint/gen_tags.vim#83]
Tpope's [vim-fugitive](https://github.com/tpope/vim-fugitive) plugin creates a temporary 'fugitive:' directory when the :Gdiff, :Gvdiff, :Gsdiff, and possibly other commands are issued. If g:gen_tags#use_cache_dir is set to 0, gen_tags will create a tags file for that directory, preventing it from being deleted, which in turn causes it to show up in the git index, as well as getting in the way of things such as go fmt.

How to reproduce:
* setup vim with [fugitive.vim](https://github.com/tpope/vim-fugitive) and gen_tags
* set g:gen_tags#use_cache_dir = 0
* open a file in a git repo
* run :Gdiff

**Comment by jsfaint** [comment]
Sorry for the late reply.
I can't reproduce this issue.
If `g:gen_tags#use_cache_dir` is set to 0, `gen_tags.vim` will only create a folder `tags_dir` under `.git`.

**Comment by jsfaint** [comment]
@ian-howell Any updates?

**Comment by jsfaint** [comment]
Close, since there is no update for a long term
If you have any update, please reopen it. thanks
