### ISSUE TITLE
[feature request] Highlight tags

### ISSUE THREAD

**Issue by reidrac** [jsfaint/gen_tags.vim#84]
I find this quite useful in vim-easytags, and I think that's the only thing that IMHO gen_tags.vim is missing for being perfect.

It periodically highlights some of the tags (functions as Keywords I think).

Thanks a lot for this plugin!

**Comment by jsfaint** [comment]
Sorry I think `gen_tags` should focus on the generate and update only.
You can use [neotags.nvim](https://github.com/c0r73x/neotags.nvim) instead.
It is like vim-easytags and support async which will not forze your editor, but the only disadvantage is it requires neovim

**Comment by jsfaint** [comment]
And there is another highlight plugin [chromatica.nvim](https://github.com/arakashic/chromatica.nvim) for C family which is pretty good too

**Comment by reidrac** [comment]
Fair enough! Thanks for your suggestions.
