### ISSUE TITLE
set ctag rules per filetype

### ISSUE THREAD

**Issue by AdrienLemaire** [jsfaint/gen_tags.vim#87]
I understand that gen_tags creates a config per project, but my projects are usually a bunch python backend, and typescript/es6/react/html/css/etc frontend, so I'd like ctags to generate tags smartly depending on the file I'm in.

I have not managed to get a result satisfying, eg jumping to some json file when Ctrl-] on a python import.

Reading through the `gen_tags.txt` help file, I cannot figure this out.
I tried from a python file to add `–python-kinds=-i` (following [this post](https://weicode.wordpress.com/2018/05/01/configuring-ctags-for-python-and-vim/)) in the `:EditExt` file, then ran `GenCtags`, but didn't get a good result

![](https://i.imgur.com/K4zqFoX.gif)

This example is me trying to jump to the definition of a django template, but instead of the expected `base.html` file, I arrive on a totally unexpected `welcome_page.css`.

```vim
Plug 'jsfaint/gen_tags.vim'
Plug 'tweekmonster/django-plus.vim', { 'for': ['python', 'htmldjango', 'html'] }
```

```console
$ vim -v
NVIM v0.3.4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.3.4/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

$ ctags --version
Universal Ctags 0.0.0(c45511a3), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Aug 24 2018, 02:04:45
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +iconv, +option-directory, +xpath, +json, +interactive, +sandbox, +yaml


```

Do you have suggestions or a link to the documentation explain how to properly setup a ctag conf for a project?

**Comment by jsfaint** [comment]
You can refer this comment 😄 
https://github.com/jsfaint/gen_tags.vim/issues/47#issuecomment-392410996

**Comment by AdrienLemaire** [comment]
Thanks for the reply @jsfaint. After reading a bit, I'm thinking of having 2 git ctags hooks, one for the frontend and one of the backend.

For the time being, I removed the frontend stuff and am focusing on getting good python/django definitions. I created [an SO thread here](https://stackoverflow.com/questions/55755583/how-to-configure-ctags-to-better-choose-the-definition-file-for-the-tag-under-th), would love it if you could take a look over there.

Closing this issue
