### ISSUE TITLE
(Neovim) Cannot redefine function <SNR>59_wrap: It is in use

### ISSUE THREAD

**Issue by joereynolds** [jsfaint/gen_tags.vim#9]
Hi,

Great looking plugin, huge fan of gtags.

I've just tried it out and whenever I try and `:wq` on a file it gives me the following error message
```
Error detected while processing function 4[30]..<SNR>22_callback:                  
line   33:                                                                         
Vim(function):E127: Cannot redefine function <SNR>59_wrap: It is in use    
```

These are the config options I have for gen_tags in my `init.vim` file

```
"gen_tags
let g:gen_tags#ctags_auto_gen = 1
let g:gen_tags#gtags_auto_gen = 1
```
I am using xubuntu.

**Comment by jsfaint** [comment]
It's weird, I can't reproduce it on archlinux, windows and macOS.
Can you give some more info, please?
Like gen_tags.vim git commit id, your codebase size and etc
Thanks

----
**UPDATE**
Maybe it was caused by fcf7e1de7012a0332fd83a0cd443c217786bdf9e
If you revert this commit, can you reproduce this issue?
```
git revert fcf7e1de7012a0332fd83a0cd443c217786bdf9e
```

**Comment by jsfaint** [comment]
Close by mistake. Sorry 😢 
@joereynolds I rewrite job control related function. Please test with latest master.
Thanks

**Comment by joereynolds** [comment]
Hey @jsfaint , that's fixed the generation of all things gtag related :D!
The only problem is (and I didn't mention this before) is that the `tags` file from ctags is never generated :(

```
joe@PC1596:~/code/th$ which ctags
/usr/local/bin/ctags
````

I've tested it on large codebases (500,000+ lines) and small codebases (1000 lines) and only GNU-Global related stuff is generated

**Comment by jsfaint** [comment]
@joereynolds The ctags files is under `~/.cache/tags_dir/`, not the project directory.
Did you checked that directory already?

**Comment by joereynolds** [comment]
My bad, seems to have worked then. Thanks!

**Comment by jsfaint** [comment]
I fixed a minor issue found in the previous commit. 😄 
Thanks for using this plugin @joereynolds
